import { faAngleLeft, faAngleRight, faArrowCircleDown, faArrowCircleLeft, faArrowCircleRight, faArrowCircleUp, faBatteryFull, faChartBar, faChartLine, faCheckCircle, faClock, faCogs, faDoorClosed, faDoorOpen, faFan, faFire, faHistory, faInfo, faInfoCircle, faMinus, faMinusSquare, faNotEqual, faPencilAlt, faPlay, faPlayCircle, faPlug, faPlus, faPlusSquare, faSave, faSearch, faSnowflake, faStop, faSun, faSyncAlt, faTimes, faTimesCircle, faTrashAlt, faUndo, faUser, faUserCog, faUserPlus } from "@fortawesome/free-solid-svg-icons";

export  const  FA_ICONS = {
  faFan: faFan,
  faFire: faFire,  
  faSnowflake: faSnowflake, 
  faDoorOpen: faDoorOpen,
  faDoorClosed: faDoorClosed,
  faAngleRight: faAngleRight,
  faAngleLeft: faAngleLeft,
  faPlus: faPlus,
  faPencilAlt: faPencilAlt,
  faTrashAlt: faTrashAlt,
  faArrowCircleRight: faArrowCircleRight,
  faUndo: faUndo,
  faPlusSquare: faPlusSquare,
  faMinusSquare: faMinusSquare, 
  faCheckCircle: faCheckCircle,
  faArrowCircleLeft: faArrowCircleLeft,
  faTimesCircle: faTimesCircle,
  faInfo: faInfo,
  faSave: faSave,
  faSyncAlt: faSyncAlt,
  faUserPlus: faUserPlus,
  faUser:faUser,
  faUserCog: faUserCog,
  faCogs:faCogs,
  faMinus: faMinus,
  faTimes: faTimes,
  faPlay: faPlay,
  faClock: faClock,
  faStop: faStop,
  faPlayCircle: faPlayCircle,
  faSearch: faSearch,
  faArrowCircleUp: faArrowCircleUp,
  faArrowCircleDown: faArrowCircleDown,
  faHistory:faHistory,
  faChartLine: faChartLine,
  faPlug: faPlug,
  faSun: faSun,
  faInfoCircle: faInfoCircle,
  faNotEqual: faNotEqual,
  faBatteryFull:faBatteryFull,
  faChartBar: faChartBar,

}

